(let* ((coding-system-for-read 'utf-8)
       (coding-system-for-write 'utf-8)
       (nav "\n#+BEGIN_export html\n<nav>\n  <ul>\n    <li><a href=\"#procesamiento-robos\">Procesamiento de Robos</a></li>\n    <li><a href=\"#ieee-754\">IEEE 754</a></li>\n    <li><a href=\"#buenos-aires-weather\">Buenos Aires Weather</a></li>\n  </ul>\n</nav>\n#+END_export\n")
       (sections "\n#+BEGIN_export html\n<section id=\"procesamiento-robos\">\n#+END_export\n\n#+INCLUDE: \"procesamiento_robos.org\" :lines \"16-\"\n\n#+BEGIN_export html\n</section>\n\n<section id=\"ieee-754\">\n#+END_export\n\n#+INCLUDE: \"ieee754.org\" :lines \"18-\"\n\n#+BEGIN_export html\n</section>\n\n<section id=\"buenos-aires-weather\">\n#+END_export\n\n#+INCLUDE: \"buenos_aires_weather.org\" :lines \"16-\"\n\n#+BEGIN_export html\n</section>\n\n<script>\ndocument.querySelectorAll('nav a').forEach(anchor => {\n    anchor.addEventListener('click', function (e) {\n        e.preventDefault();\n        const targetId = this.getAttribute('href').substring(1);\n        const targetElement = document.getElementById(targetId);\n        if (targetElement) {\n            targetElement.scrollIntoView({ behavior: 'smooth' });\n        }\n    });\n});\n</script>\n#+END_export\n")
       (content (with-temp-buffer
                  (insert-file-contents "#index.org#")
                  (goto-char (point-min))
                  (when (re-search-forward "^#\\+cite_export:" nil t)
                    (insert nav))
                  (goto-char (point-max))
                  (insert sections)
                  (buffer-string))))
  (with-temp-buffer
    (insert content)
    (write-region (point-min) (point-max) "index.org")))
